name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        run: |
          sudo apt update 
          sudo apt install -y curl git
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y nodejs

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the app directory
            sudo mkdir -p /home/ubuntu/app
            sudo chown -R ubuntu:ubuntu /home/ubuntu/app
            
            cd /home/ubuntu/app

            # If it's not a Git repo, clone the repo
            if [ ! -d ".git" ]; then
              git clone https://github.com/amit2111github/ec2-ci-cd.git 
            else
              git pull origin main
            fi

            # Install dependencies and start the app
            npm install
            npm run start
